version: '3'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    expose:
      - "8000"
    env_file:
      - ./.env
    environment:
      SET_WEBHOOK: 1
    entrypoint: ["/opt/app/run_asgi.sh"]
    depends_on:
      - db
  
  bot:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: sh -c "python manage.py start_bot"
    depends_on:
      - db
      - web
    env_file:
      - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:1.19.2
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
      - ./nginx_dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_dev/configs:/etc/nginx/conf.d:ro
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume:
