# Generated by Django 4.2.7 on 2024-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nps", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INCORRECT", "Некорректный отзыв"),
                    ("WRONG_CLINIC", "Отзыв не о нашей клинике"),
                ],
                null=True,
                verbose_name="Причина отказа",
            ),
        ),
    ]
