# Generated by Django 4.2.7 on 2023-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("enote_id", models.CharField(max_length=150)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="", max_length=100)),
                ("middle_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(default="", max_length=12)),
                ("tg_chat_id", models.IntegerField(default=0, null=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
