# Generated by Django 4.2.7 on 2023-12-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="client_auth.discountcardcategory",
                to_field="enote_id",
                verbose_name="Категория карты",
            ),
        ),
    ]
