# Generated by Django 4.2.7 on 2024-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tg_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram Id"
            ),
        ),
    ]
