# Generated by Django 4.2.7 on 2023-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_enote_id",
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
