# Generated by Django 4.2.7 on 2023-12-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=False,
                verbose_name="Телефон",
            ),
        ),
        migrations.CreateModel(
            name="BlockedClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заблокированный клиент",
                "verbose_name_plural": "Заблокированные клиенты",
            },
        ),
    ]
