# Generated by Django 4.2.7 on 2024-04-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0002_alter_client_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="in_blacklist",
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
    ]
