# Generated by Django 4.2.7 on 2023-12-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0002_alter_client_phone_number_blockedclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Телефон"
            ),
        ),
    ]
