# Generated by Django 4.2.7 on 2023-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0002_blockedclient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockedclient",
            options={
                "verbose_name": "Заблокированный клиент",
                "verbose_name_plural": "Заблокированные клиенты",
            },
        ),
        migrations.AlterField(
            model_name="blockedclient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
