# Generated by Django 4.2.7 on 2023-12-19 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0002_alter_discountcard_category_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscountCard",
        ),
        migrations.DeleteModel(
            name="DiscountCardCategory",
        ),
    ]
