# Generated by Django 4.2.7 on 2023-12-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0003_alter_blockedclient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedclient",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
            ),
        ),
        migrations.AlterField(
            model_name="blockedclient",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
