# Generated by Django 4.2.7 on 2023-12-26 12:00

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("client_auth", "0005_client_bonuses_balance"),
        ("client_auth", "0006_remove_client_bonuses_balance"),
    ]

    dependencies = [
        (
            "client_auth",
            "0002_blockedclient_squashed_0004_alter_blockedclient_client_and_more",
        ),
    ]

    operations = []
