# Generated by Django 4.2.7 on 2024-01-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0006_alter_blockedclient_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="client_auth.client"
            ),
        ),
    ]
