# Generated by Django 4.2.7 on 2024-01-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0007_alter_blockedclient_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="weight",
        ),
        migrations.AlterField(
            model_name="patient",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.animalkind",
                verbose_name="Вид",
            ),
        ),
    ]
