# Generated by Django 4.2.7 on 2024-02-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="client_auth.animalkind",
                verbose_name="Вид",
            ),
        ),
    ]
