# Generated by Django 4.2.7 on 2024-03-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0010_alter_patient_client_alter_patient_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="blockedclient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blockedclient",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="Причина"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
    ]
