# Generated by Django 4.2.7 on 2023-12-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Номер карты"
            ),
        ),
    ]
