# Generated by Django 4.2.7 on 2023-12-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0001_initial"),
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
    ]
