# Generated by Django 4.2.7 on 2024-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonusaccrual",
            name="reason",
            field=models.CharField(
                choices=[
                    ("BIRTHDAY", "День рождения пациента"),
                    ("REGISTRATION", "Бонус за регистрацию"),
                    ("REFERAL_SENDER", "Бонус за приглашенного клиента"),
                    ("REFERAL_GETTER", "Бонус за получение приглашения"),
                    ("REVIEW", "Бонус за отзыв"),
                    ("MANUAL", "Ручное начисление"),
                ],
                max_length=200,
                verbose_name="Причина начисления",
            ),
        ),
    ]
