# Generated by Django 4.2.7 on 2023-12-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0002_alter_client_phone_number_blockedclient"),
        ("bonuses", "0002_alter_discountcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discount_cards",
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.CreateModel(
            name="BonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("sum", models.IntegerField()),
                ("datetime", models.DateTimeField()),
                (
                    "discount_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bonus_transactions",
                        to="bonuses.discountcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция по бонусной карте",
                "verbose_name_plural": "Транзакции по бонусной карте",
            },
        ),
    ]
