# Generated by Django 4.2.7 on 2024-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0002_alter_bonusaccrual_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="payment_percent",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Процент оплаты бонусами"
            ),
        ),
    ]
