# Generated by Django 4.2.7 on 2023-12-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0002_alter_discountcard_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("sum", models.IntegerField()),
                ("transaction_datetime", models.DateTimeField()),
                (
                    "discount_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bonuses.discountcard",
                    ),
                ),
            ],
        ),
    ]
