# Generated by Django 4.2.7 on 2024-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0003_program_payment_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonusaccrual",
            name="comment",
            field=models.TextField(
                blank=True,
                max_length=750,
                null=True,
                verbose_name="Комментарий при ручном начислении",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="payment_percent",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Максимальный процент оплаты бонусами"
            ),
        ),
    ]
