# Generated by Django 4.2.7 on 2024-01-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0003_alter_discountcard_client_bonustransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField()),
                ("registration_bonus_amount", models.PositiveIntegerField()),
                ("new_client_bonus_amount", models.PositiveIntegerField()),
                ("review_bonus_amount", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Программа лояльности",
                "verbose_name_plural": "Программы лояльности",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("cashback_amount", models.PositiveIntegerField()),
                ("start_amount", models.PositiveIntegerField()),
                ("end_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bonuses.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус программы лояльности",
                "verbose_name_plural": "Статусы программы лояльности",
            },
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="one_program_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                fields=("program", "name"), name="unique_name_per_program"
            ),
        ),
    ]
