# Generated by Django 4.2.7 on 2024-01-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0004_program_status_program_one_program_active_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="program",
            name="one_program_active",
        ),
        migrations.AlterField(
            model_name="status",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="bonuses.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="Только одна программа может быть активна",
            ),
        ),
    ]
