# Generated by Django 4.2.7 on 2024-01-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0005_remove_program_one_program_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(
                help_text="Эта информация будет показана клиентам",
                verbose_name="Описание программы",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Имя программы"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="new_client_bonus_amount",
            field=models.PositiveIntegerField(verbose_name="Бонус за нового клиента"),
        ),
        migrations.AlterField(
            model_name="program",
            name="registration_bonus_amount",
            field=models.PositiveIntegerField(verbose_name="Бонус за регистрацию"),
        ),
        migrations.AlterField(
            model_name="program",
            name="review_bonus_amount",
            field=models.PositiveIntegerField(verbose_name="Бонус за отзыв"),
        ),
        migrations.AlterField(
            model_name="status",
            name="cashback_amount",
            field=models.PositiveIntegerField(verbose_name="Кэшбек"),
        ),
        migrations.AlterField(
            model_name="status",
            name="end_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Конечное значение статуса"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                help_text="Эта информация будет показана клиентам",
                max_length=150,
                verbose_name="Название статуса",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statuses",
                to="bonuses.program",
                verbose_name="Программа",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="start_amount",
            field=models.PositiveIntegerField(
                verbose_name="Начальное значение статуса"
            ),
        ),
    ]
