# Generated by Django 4.2.7 on 2024-02-06 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
        ("bonuses", "0007_bonusaccural"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BonusAccural",
            new_name="BonusAccrual",
        ),
        migrations.RenameField(
            model_name="bonusaccrual",
            old_name="accured",
            new_name="accrued",
        ),
    ]
