# Generated by Django 4.2.7 on 2024-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
        ("bonuses", "0007_bonusaccural"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BonusAccural",
            new_name="BonusAccrual",
        ),
    ]
