# Generated by Django 4.2.7 on 2024-02-01 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0008_rename_bonusaccural_bonusaccrual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bonusaccrual",
            old_name="accured",
            new_name="accrued",
        ),
    ]
