# Generated by Django 4.2.7 on 2024-02-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0008_rename_bonusaccural_bonusaccrual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="birthday_bonus_amount",
            field=models.PositiveIntegerField(verbose_name="Бонус на день рождения"),
            preserve_default=False,
        ),
    ]
