# Generated by Django 4.2.7 on 2024-02-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0010_alter_patient_client_alter_patient_kind"),
        ("bonuses", "0009_program_birthday_bonus_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promocode", models.CharField(verbose_name="Промокод")),
                ("status", models.BooleanField(default=False, verbose_name="Выдано")),
                (
                    "client_issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                        verbose_name="Выдавший пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендация",
                "verbose_name_plural": "Рекомендации",
            },
        ),
    ]
