# Generated by Django 4.2.7 on 2024-02-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0010_alter_patient_client_alter_patient_kind"),
        ("bonuses", "0010_recommendation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="status",
            new_name="issued",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="client_issuer",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Пригласивший пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=None, verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendation",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="promocode",
            field=models.CharField(unique=True, verbose_name="Промокод"),
        ),
    ]
