# Generated by Django 4.2.7 on 2024-02-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0010_alter_patient_client_alter_patient_kind"),
        ("bonuses", "0011_rename_status_recommendation_issued_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Пригласивший клиент",
            ),
        ),
    ]
