# Generated by Django 4.2.7 on 2024-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0012_alter_recommendation_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удалена"),
        ),
        migrations.DeleteModel(
            name="BonusTransaction",
        ),
    ]
