# Generated by Django 4.2.7 on 2023-12-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Kind",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="VisitKind",
            fields=[
                ("enote_id", models.CharField(max_length=250)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250)),
                ("birth_date", models.DateField()),
                ("weight", models.CharField(max_length=20)),
                ("time_of_death", models.DateTimeField(default="")),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.breed",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="endpoints.kind"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("client_enote_id", models.CharField(max_length=150)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="", max_length=100)),
                ("middle_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("position", models.CharField(max_length=250)),
                ("photo", models.ImageField(upload_to="")),
                ("detail_info", models.TextField(default="")),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="endpoints.specialization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="breed",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="endpoints.kind"
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=200)),
                ("type", models.CharField(default="", max_length=250)),
                ("new_client", models.BooleanField(default=True)),
                ("status", models.CharField(default="", max_length=250)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="endpoints.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="endpoints.patient",
                    ),
                ),
                (
                    "visit_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="endpoints.visitkind",
                    ),
                ),
            ],
        ),
    ]
