version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    user: postgres
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
  bot:
    restart: always
    build: .
    command: sh -c "python manage.py start_bot && python manage.py migrate"
    depends_on:
      - postgres
      - web
    env_file:
      - ./.env
volumes:
  db: