apiVersion: apps/v1
kind: Deployment
metadata:
  name: vetbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vetbot
      version: '<VERSION>'
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vetbot
        version: '<VERSION>'
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.5"
              memory: 500Mi
        - name: bot
          image: 'registry.divlab.tech/tg_bots/vet_bot:<TAG>'
          envFrom:
            - secretRef:
                name: 'vetbot-secret'
          command: ["python", "manage.py", "start_bot"]
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.5"
              memory: 500Mi
        - name: 'web'
          image: 'registry.divlab.tech/tg_bots/vet_bot:<TAG>'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: 'vetbot-secret'
          volumeMounts:
            - mountPath: /app/var
              name: var-volume
          resources:
            limits:
              cpu: "2"
              memory: 2000Mi
            requests:
              cpu: "2"
              memory: 2000Mi
      volumes:
        - name: var-volume
          emptyDir: {}