# Generated by Django 4.2.7 on 2024-01-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_auth", "0008_remove_patient_weight_alter_patient_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="ID в еноте",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название специализации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Врачебная специализация",
                "verbose_name_plural": "Врачебные специализации",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="ID в еноте",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
                (
                    "detail_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание врача"
                    ),
                ),
                (
                    "fired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометить на удаление"
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="doctors",
                        to="appointment.specialization",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="ID в еноте",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKING", "Бронирование"),
                            ("PLANNED", "Запланировано"),
                            ("IN_CLINIC", "В клинике"),
                            ("CLINIC_APPOINTMENT", "На приеме"),
                            ("REGISTRATION", "Оформление"),
                            ("COMPLETED", "Завершено"),
                            ("CLIENTS_REFUSAL", "Отказ"),
                            ("IN_INPATIENTS", "Стационар"),
                            ("DISCHARGED", "Выписан из стационара"),
                        ],
                        default="PLANNED",
                        verbose_name="Статус записи",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="Время записи")),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, verbose_name="Пометить на удаление"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appointment.doctor",
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приём",
            },
        ),
    ]
