# Generated by Django 4.2.7 on 2024-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "show_in_bot",
                    models.BooleanField(default=True, verbose_name="Показывать в боте"),
                ),
            ],
            options={
                "verbose_name": "Врачебная должность",
                "verbose_name_plural": "Врачебные должности",
            },
        ),
        migrations.RemoveField(
            model_name="specialization",
            name="enote_id",
        ),
        migrations.AddField(
            model_name="doctor",
            name="show_in_bot",
            field=models.BooleanField(default=False, verbose_name="Показывать в боте"),
        ),
        migrations.AddField(
            model_name="specialization",
            name="show_in_bot",
            field=models.BooleanField(default=True, verbose_name="Показывать в боте"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="detail_info",
            field=models.TextField(
                blank=True,
                max_length=700,
                null=True,
                verbose_name="Описание для клиентов",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Размер фото не должен превышать 3 Мб",
                null=True,
                upload_to="doctors/",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                related_name="doctors",
                to="appointment.specialization",
                verbose_name="Специализации",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                related_name="doctors",
                to="appointment.position",
                verbose_name="Должности",
            ),
        ),
    ]
