# Generated by Django 4.2.7 on 2024-01-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.patient",
                verbose_name="Пациент",
            ),
        ),
    ]
