# Generated by Django 4.2.7 on 2024-01-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
        ("appointment", "0002_appointment_client_alter_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enote_id",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="ID в еноте",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата")),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвойс",
                "verbose_name_plural": "Инвойсы",
            },
        ),
    ]
