# Generated by Django 4.2.7 on 2024-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_position_remove_specialization_enote_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Подтверждена"),
        ),
    ]
