# Generated by Django 4.2.7 on 2024-01-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_appointment_client_alter_appointment_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="appointment.doctor",
                verbose_name="Доктор",
            ),
        ),
    ]
