# Generated by Django 4.2.7 on 2024-01-25 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0003_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Инвойс", "verbose_name_plural": "Инвойсы"},
        ),
    ]
