# Generated by Django 4.2.7 on 2024-01-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_auth", "0009_weighing"),
        ("appointment", "0003_alter_appointment_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="client_auth.client",
                verbose_name="Клиент",
            ),
        ),
    ]
