FROM python:3.10

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE 'bot_admin.settings'

RUN apt-get update \
    && apt-get install -y netcat-traditional \
    && apt-get install -y gettext

COPY requirements.txt requirements.txt
COPY entrypoint.sh entrypoint.sh

RUN mkdir -p /opt/app/static/ \
    && mkdir -p /opt/app/media/ \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

RUN sed -i 's/\r$//g' /opt/app/entrypoint.sh \
    && chmod +x  /opt/app/entrypoint.sh

EXPOSE 8000
