# Generated by Django 4.2.7 on 2023-12-06 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("topic", models.CharField(choices=[], max_length=250)),
                ("state", models.CharField(choices=[], max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "dialogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dialogue.dialogue",
                    ),
                ),
            ],
        ),
    ]
