apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "deployment-postgres.yaml"
  - "pvc-postgres.yaml"
  - "service-postgres.yaml"
secretGenerator:
  - name: "postgres-vetbot-secrets"
    envs:
      - ".env"
    type: "Opaque"
