# Generated by Django 4.2.7 on 2024-03-14 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_auth", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
