# Generated by Django 4.2.7 on 2024-03-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="admin",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="admin",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="email",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="password",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="username",
        ),
        migrations.AddField(
            model_name="admin",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
