# Generated by Django 4.2.7 on 2024-03-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_auth", "0002_alter_admin_managers_remove_admin_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="tg_chat_id",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Telegram Id"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
