# Generated by Django 4.2.7 on 2023-11-29 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dialog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breed",
            name="kindEnoteId",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="clientEnoteId",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Breed",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Kind",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="VisitKind",
        ),
    ]
