# Generated by Django 4.2.7 on 2023-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dialog", "0002_alter_client_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="clientTelegramid",
            field=models.IntegerField(null=True),
        ),
    ]
