# Generated by Django 4.2.7 on 2023-11-28 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dialog", "0003_alter_client_clienttelegramid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="clientTelegramid",
            new_name="clientTelegramId",
        ),
    ]
