# Generated by Django 4.2.7 on 2023-12-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Kind",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("enote_id", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250)),
                ("birth_date", models.DateField()),
                ("weight", models.FloatField()),
                ("time_of_death", models.DateTimeField(default="")),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.breed",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client_auth.client",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="endpoints.kind"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="breed",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="endpoints.kind"
            ),
        ),
    ]
